version: '3'

services:
  traefik:
    image: "traefik:v2.10"
    restart: always
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    image: europe-west9-docker.pkg.dev/keymoov/keymoov-frontend/latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`keymoov.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  backend:
    image: europe-west9-docker.pkg.dev/keymoov/keymoov-backend/latest
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.keymoov.com`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  play:
    image: europe-west9-docker.pkg.dev/keymoov/keymoov-play-service/latest
    restart: always
    environment:
      - SERVER_PORT=80
      - BUCKET_NAME=${BUCKET_NAME}
      - PROJECT_ID=${PROJECT_ID}
      - KEY_FILENAME=/googleKey.json
    volumes:
      - ${KEY_FILENAME}:/googleKey.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.play.rule=Host(`play.keymoov.com`)"
      - "traefik.http.routers.play.entrypoints=web"
      - "traefik.http.services.play.loadbalancer.server.port=80"

  upload:
    image: europe-west9-docker.pkg.dev/keymoov/keymoov-upload-service/latest
    restart: always
    environment:
      - SERVER_PORT=80
      - BUCKET_NAME=${BUCKET_NAME}
      - PROJECT_ID=${PROJECT_ID}
      - KEY_FILENAME=/googleKey.json
      - FILE_SIZE_LIMIT=${UPLOAD_FILE_SIZE_LIMIT}
    volumes:
      - ${KEY_FILENAME}:/googleKey.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.upload.rule=Host(`upload.keymoov.com`)"
      - "traefik.http.routers.upload.entrypoints=web"
      - "traefik.http.services.upload.loadbalancer.server.port=80"

  boards:
    image: europe-west9-docker.pkg.dev/keymoov/keymoov-boards/latest
    restart: always
    environment:
      - SERVER_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boards.rule=Host(`boards.keymoov.com`)"
      - "traefik.http.routers.boards.entrypoints=web"
      - "traefik.http.services.boards.loadbalancer.server.port=80"
