version: "3"

services:
    upload:
        image: europe-west9-docker.pkg.dev/keymoov/keymoov-upload-service/latest
        command: ls -la node_modules/@ffmpeg-installer/ffmpeg/node_modules
        environment:
            - SERVER_PORT=80
            - BUCKET_NAME=${BUCKET_NAME}
            - PROJECT_ID=${PROJECT_ID}
            - KEY_FILENAME=/googleKey.json
        volumes:
            - ${KEY_FILENAME}:/googleKey.json:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.upload.rule=Host(`upload.keymoov.com`)"
            - "traefik.http.routers.upload.entrypoints=web"
